# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Commit Stage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v12.18
      uses: actions/setup-node@v1
      with:
        node-version: 12.18.x
    - run: npm ci
    - run: npm run typecheck
    - run: npm run lint
    - run: npm run build
    - run: npm test
